// OrbitSaveGame.cpp
// Implements binary serialization for the OrbitSaveGame class

#include "OrbitSaveGame.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/BufferArchive.h"
#include "Serialization/MemoryReader.h"

//////////////////////////////////////////////////////////////////////////
// UOrbitSaveGame

UOrbitSaveGame::UOrbitSaveGame()
{
	// Default constructor
}

//////////////////////////////////////////////////////////////////////////
// Serialization helpers

// Serializes the entire save game object into a binary array
bool UOrbitSaveGame::SerializeToArray(TArray<uint8>& OutData) const
{
	FBufferArchive Ar;
	Ar << *this;  // Uses the overloaded << operator for USaveGame
	if (Ar.Num() == 0)
	{
		Ar.FlushCache();
		Ar.Empty();
		return false;
	}
	OutData = Ar.GetBuffer();
	Ar.FlushCache();
	Ar.Empty();
	return true;
}

// Deserializes the entire save game object from a binary array
bool UOrbitSaveGame::DeserializeFromArray(const TArray<uint8>& InData)
{
	FMemoryReader Ar(InData);
	Ar << *this;  // Uses the overloaded << operator for USaveGame
	return true;
}

//////////////////////////////////////////////////////////////////////////
// File I/O

// Saves the current state to a .sav file
bool UOrbitSaveGame::SaveGameToFile(const FString& FilePath) const
{
	TArray<uint8> SaveData;
	if (!SerializeToArray(SaveData))
	{
		UE_LOG(LogTemp, Error, TEXT("OrbitSaveGame: Failed to serialize data."));
		return false;
	}

	if (!FFileHelper::SaveArrayToFile(SaveData, *FilePath))
	{
		UE_LOG(LogTemp, Error, TEXT("OrbitSaveGame: Failed to write file %s."), *FilePath);
		return false;
	}

	UE_LOG(LogTemp, Log, TEXT("OrbitSaveGame: Successfully saved to %s."), *FilePath);
	return true;
}

// Loads a save game from a .sav file
UOrbitSaveGame* UOrbitSaveGame::LoadGameFromFile(const FString& FilePath)
{
	if (!FPaths::FileExists(FilePath))
	{
		UE_LOG(LogTemp, Warning, TEXT("OrbitSaveGame: File %s does not exist."), *FilePath);
		return nullptr;
	}

	TArray<uint8> LoadData;
	if (!FFileHelper::LoadFileToArray(LoadData, *FilePath))
	{
		UE_LOG(LogTemp, Error, TEXT("OrbitSaveGame: Failed to read file %s."), *FilePath);
		return nullptr;
	}

	UOrbitSaveGame* LoadedGame = NewObject<UOrbitSaveGame>();
	if (!LoadedGame->DeserializeFromArray(LoadData))
	{
		UE_LOG(LogTemp, Error, TEXT("OrbitSaveGame: Failed to deserialize data from %s."), *FilePath);
		return nullptr;
	}

	UE_LOG(LogTemp, Log, TEXT("OrbitSaveGame: Successfully loaded from %s."), *FilePath);
	return LoadedGame;
}

//////////////////////////////////////////////////////////////////////////
// USaveGame serialization

// The following operator overloads are required for USaveGame to serialize its properties.
// They are automatically generated by the UE4/UE5 reflection system, but we provide explicit
// overloads here for clarity and to ensure binary compatibility.

void UOrbitSaveGame::Serialize(FArchive& Ar)
{
	Super::Serialize(Ar);  // Serialize base USaveGame data

	// Example: serialize a simple array of positions and rotations
	Ar << OrbitPositions;
	Ar << OrbitRotations;

	// If you have additional custom data, serialize it here
	// Ar << CustomData;
}
